#!/bin/bash
#set environment
logfile=/SmoothTorque/restart.log
#PID=`ps -eo 'tty pid args' | grep vg | grep -v grep | tr -s ' ' | cut -f2 -d ' '`
PID=`/bin/pidof -sx vg`
COUNTER="/tmp/${0##*/}"


if [ -z "$PID" ]
then
#Run the process
cd /SmoothTorque
screen -dmS smoothtorque ./vg 
echo "Started Process at `date`" >> $logfile
else
echo "Process is already Running with PID=$PID"
fi



