<form name="myForm">
	<table border="0">
		<tr>
			<td colspan="2"><img src="images/logo2.png"></td>
		</tr>
		<tr>
			<td>Are you sure you want to delete this entry?</td>
		</tr>
		<tr>
			<td><input type="button" value="Yes" style="width:60px" onclick="closeMessage();verify(true)">
			<input type="button" value="No" style="width:60px" onclick="closeMessage();verify(false)"></td>
		</tr>
	</table>
</form>
